name: Build and Publish npm Package

on:
  push:
    branches:
      - main  # 你可以指定要监听的分支

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 使用你项目所需的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Login to npm
        run: npm login --registry=https://registry.npmjs.org/ --scope=@your-npm-scope
        env:
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}

      - name: Version package
        run: npm run v

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PASSWORD }}  # 如果使用令牌，确保使用正确的环境变量名
